// js/languages.js
const translations = {
    en: {
      // Navigation
      dashboard: "Dashboard",
      factories: "Factories",
      processes: "Processes",
      notifications: "Notifications",
      analytics: "Analytics",
      userManagement: "User Management",
      approvals: "Approvals",
      masterDB: "Master DB",
      customerManagement: "Customer Management",
      equipment: "Equipment",
      
      // Common
      searchPlaceholder: "Search...",
      loading: "Loading...",
      logout: "Logout",
      role: "Role",
      submit: "Submit",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      save: "Save",
      refresh: "Refresh",
      export: "Export",
      import: "Import",
      upload: "Upload",
      download: "Download",
      view: "View",
      add: "Add",
      create: "Create",
      update: "Update",
      filter: "Filter",
      search: "Search",
      all: "All",
      total: "Total",
      
      // Login Page
      loginTitle: "Login",
      username: "Username",
      password: "Password",
      enterUsername: "Enter username",
      enterPassword: "Enter password",
      invalidCredentials: "Invalid credentials",
      loginFailed: "Login failed",
      networkError: "Network error",
      
      // Dashboard
      factoryOverview: "Factory Overview",
      viewDetails: "Click to view factory details",
      
      // Analytics
      defectRateAnalytics: "Defect Rate Analytics",
      monthlySummary: "Monthly Summary",
      
      // Factories
      factoryListTitle: "Factory List",
      
      // User Management
      userManagementTitle: "User Management",
      searchUsers: "Search users...",
      createNewUser: "Create New User",
      firstName: "First Name",
      lastName: "Last Name",
      email: "Email",
      selectRole: "Select Role",
      factorySelection: "Factory Selection",
      loadingUsers: "Loading users...",
      accessDenied: "Access Denied",
      
      // Approvals
      approvalsTitle: "Data Approval System",
      kensa: "Inspection (Kensa)",
      press: "Press",
      slit: "Slit",
      pending: "Pending",
      hanchoApproved: "Hancho Approved",
      fullyApproved: "Fully Approved",
      rejected: "Rejected",
      pendingApproval: "Pending Hancho Approval",
      waitingKacho: "Waiting for Kacho Approval",
      correctionNeeded: "Correction Needed",
      kachoRequest: "Kacho Correction Request",
      todayTotal: "Today's Total",
      submittedToday: "Submitted Today",
      needsCorrection: "Needs Correction & Resubmission",
      hanchoAction: "Hancho Action Required",
      kachoApprovalComplete: "Kacho Approval Complete",
      currentDateOnly: "Current Date Only",
      allHistoricalData: "All Historical Data", 
      showingCurrentDate: "Showing current date data",
      showingAllData: "Showing all historical data",
      
      // Master DB
      masterProductManagement: "Master Product Management",
      csvFile: "CSV File",
      uploadPreview: "Upload & Preview",
      factory: "Factory",
      rl: "R/L",
      color: "Color",
      processEquipment: "Processing Equipment",
      searchPlaceholderMaster: "Search by part number, model, serial number, product name...",
      totalCount: "Total Count",
      withImages: "With Images",
      noImages: "No Images",
      recentlyAdded: "Recently Added",
      partNumber: "Part Number",
      serialNumber: "Serial Number",
      model: "Model",
      productName: "Product Name",
      defectRate: "Defect Rate",
      exportCSV: "Export CSV",
      exportPDF: "Export PDF",
      addNewRecord: "Add New Record",
      addNewRecordModal: "Add New Record",
      productImage: "Product Image",
      noImageAvailable: "No image available",
      uploadImage: "Upload Image",
      cancel: "Cancel",
      save: "Save",
      pleaseEnterAtLeastOneField: "Please enter at least one field.",
      recordAddedSuccessfully: "New record added successfully!",
      failedToAddRecord: "Failed to add record: ",
      
      // Equipment
      equipmentTitle: "Equipment Management",
      equipmentFilter: "Equipment Filter (by Factory)",
      dateRange: "Date Range",
      applyFilters: "Apply Filters",
      exportPDF: "Export PDF",
      totalShots: "Total Shots",
      avgShotsDay: "Avg Shots/Day", 
      avgShotsHour: "Avg Shots/Hour",
      workingHoursDay: "Working Hours/Day",
      dailyPerformanceTrend: "Daily Performance Trend",
      shots: "Shots",
      workingHours: "Working Hours",
      processQty: "Process Qty",
      defects: "Defects",
      date: "Date",
      worker: "Worker",
      time: "Time",
      entries: "entries",
      records: "records",
      show: "Show",
      noDataAvailable: "No data available for the selected filters",
      tryAdjustingFilters: "Try adjusting your date range or equipment selection",
      
      // Dashboard/Factories metrics
      totalNG: "Total NG",
      normal: "Normal",
      warning: "Warning",
      highDefectRate: "High Defect Rate",
      status: "Status",
      
      // Customer Management
      customerManagementTitle: "Customer Management",
      
      // Processes
      processesTitle: "Processes",
      
      // Notifications
      notificationsTitle: "Notifications",
      
      // Master User Admin Panel
      masterUserAdminPanel: "Master User Admin Panel",
      searchByUsernameCompanyEmail: "Search by username, company, or email...",
      createMasterUser: "Create Master User",
      companyName: "Company Name",
      databaseName: "Database Name",
      devicesOptional: "Devices (optional)",
      addDevice: "+ Add Device",
      validUntil: "Valid Until",
      database: "Database",
      devices: "Devices",
      actions: "Actions",
      resetPassword: "Reset Password",
      
      // Page titles
      dashboardTitle: "Dashboard",
      factoriesTitle: "Factories",
      processesTitle: "Processes",
      notificationsTitle: "Notifications",
      analyticsTitle: "Analytics",
      approvalsTitle: "Approvals",
      customerManagementTitle: "Customer Management",
      
      // Approval View Modes
      tableView: "Table View (Individual Approval)",
      listView: "List View (Batch Approval)",
      viewMode: "View Mode:",
      batchApproveSelected: "Batch Approve Selected",
      batchRejectSelected: "Batch Reject Selected",
      selected: "selected",
      dataUpdate: "🔄 Data Update",
      allFactories: "All Factories",
      allStatus: "All Status",
      
      // Analytics
      analytics: "Analytics",
      analyticsInsights: "Comprehensive analytics and insights from inspection data",
      totalProduction: "Total Production",
      totalDefects: "Total Defects",
      avgDefectRate: "Avg Defect Rate",
      totalFactories: "Total Factories",
      totalWorkers: "Total Workers",
      avgCycleTime: "Avg Cycle Time",
      productionTrend: "Production & Defects Trend",
      qualityTrend: "Quality Trend (Defect Rate)",
      factoryComparison: "Factory Comparison",
      defectDistribution: "Defect Distribution (By Counter)",
      workerPerformance: "Worker Performance (Top 10)",
      processEfficiency: "Process Efficiency (Avg Cycle Time)",
      dateRange: "Date Range",
      fromDate: "From Date",
      toDate: "To Date",
      today: "Today",
      last7Days: "Last 7 Days",
      last30Days: "Last 30 Days",
      last90Days: "Last 90 Days",
      thisMonth: "This Month",
      lastMonth: "Last Month",
      customRange: "Custom Range",
      exportCsv: "Export CSV",
      refresh: "Refresh",
      loadingAnalytics: "Loading analytics data...",
      noDataAvailable: "No data available for the selected date range",
      processFilter: "Process",
      allProcesses: "All Processes",
      inspectionProcess: "Inspection (kensaDB)",
      pressProcess: "Press (pressDB)",
      slitProcess: "Slit (slitDB)",
      srsProcess: "SRS (SRSDB)",
      
      // Additional common terms
      none: "None",
      selectAll: "Select All",
      deselectAll: "Deselect All",
      loading: "Loading...",
      loadingData: "Loading data...",
      loadingFactories: "Loading Factory Data...",
      pleaseWait: "Please wait while we fetch the latest information",
      error: "Error",
      success: "Success",
      warning: "Warning",
      information: "Information",
      confirmation: "Confirmation",
      yes: "Yes",
      no: "No",
      ok: "OK",
      close: "Close",
      back: "Back",
      next: "Next",
      previous: "Previous",
      page: "Page",
      of: "of",
      first: "First",
      last: "Last",
      
      // Environmental Data
      environmentalData: "Environmental Data",
      temperature: "Temperature",
      humidity: "Humidity",
      co2: "CO2",
      co2Level: "CO2 Level",
      updateData: "Update Data",
      lastUpdated: "Last Updated",
      simulatedData: "※ Simulated Data",
      refreshEnvironmentalData: "Refresh Environmental Data",
      normalRange: "Normal Range",
      temperatureRange: "18-26°C",
      humidityRange: "40-60%",
      co2Standard: "<1000ppm",
      ventilationRequired: "Ventilation Required",
      ventilationRecommended: "Ventilation Recommended",
      good: "Good",
      lowTemperatureWarning: "Low Temperature Warning",
      highTemperatureWarning: "High Temperature Warning",
      lowTemperatureAlert: "Low Temperature Alert",
      highTemperatureAlert: "High Temperature Alert",
      dryAlert: "Dry Alert",
      highHumidityAlert: "High Humidity Alert",
      dryWarning: "Dry Warning",
      highHumidityWarning: "High Humidity Warning",
      
      // Physical Sensors
      physicalSensors: "Physical Sensors",
      sensors: "Sensors",
      sensorCount: "sensors",
      highestTemp: "Highest Temp",
      averageHumidity: "Avg Humidity",
      viewDetails: "View Details",
      lastUpdate: "Last Updated",
      sensorHistory: "Sensor History",
      temperatureHistory: "Temperature History",
      noDataLast30Days: "No sensor data in the last 30 days",
      records: " records",
      latestTemperature: "Latest Temperature",
      clickForHistory: "Click for detailed history",
      last30Days: "Sensor data from the last 30 days",
      noSensorData: "No sensor data",
      allSensors: "All Sensors",
      sensorDetails: "Sensor Details",
      activeSensors: "Active Sensors",
      sensor: "Sensor",
      loadingSensorData: "Loading sensor data...",
      failedToLoad: "Failed to load data",
      items: "items",
      previous: "Previous",
      next: "Next",
      dataUpdatesEvery15Min: "Sensor data is updated every 15 minutes",
      
      // WBGT (Wet Bulb Globe Temperature)
      wbgt: "WBGT",
      extremeHeat: "Extreme Heat",
      dangerousHeat: "Dangerous Heat", 
      heatCaution: "Heat Caution",
      safe: "Safe",
      
      // Analytics Page
      analyticsTitle: "Analytics",
      analyticsSubtitle: "Inspection Data Analysis & Insights",
      periodSelection: "Period Selection",
      last30Days: "Last 30 Days",
      last7Days: "Last 7 Days",
      last3Months: "Last 3 Months",
      customRange: "Custom Range",
      startDate: "Start Date",
      endDate: "End Date",
      process: "Process",
      inspection: "Inspection (kensaDB)",
      press: "Press (pressDB)",
      slit: "Slit (slitDB)",
      srs: "SRS (SRSDB)",
      factoryFilter: "Factory Filter",
      allFactories: "All Factories",
      csvExport: "CSV Export",
      update: "Update",
      
      // Analytics KPI Cards
      totalProduction: "Total Production",
      totalDefects: "Total Defects",
      defectRate: "Defect Rate",
      factoryCount: "Factory Count",
      workerCount: "Worker Count",
      avgCycleTime: "Avg Cycle Time",
      minutes: "minutes",
      
      // Analytics Charts
      productionDefectTrend: "Production & Defect Trend",
      production: "Production",
      defects: "Defects",
      qualityTrendDefectRate: "Quality Trend (Defect Rate)",
      defectRatePercent: "Defect Rate (%)",
      factoryPerformance: "Factory Performance",
      workerPerformance: "Worker Performance (Top 10)",
      equipmentEfficiency: "Equipment Efficiency (Top 10)",
      equipment: "Equipment",
      cycleTime: "Cycle Time",
      defectDistributionByProcess: "Defect Distribution (by Process)",
      temperatureTrend: "Temperature Trend",
      temperature: "Temperature",
      celsius: "°C",
      humidityTrend: "Humidity Trend",
      humidity: "Humidity",
      percent: "%",
      
      // Chart Labels
      counter1: "Counter 1",
      counter2: "Counter 2", 
      counter3: "Counter 3",
      counter4: "Counter 4",
      counter5: "Counter 5",
      counter6: "Counter 6",
      counter7: "Counter 7",
      counter8: "Counter 8",
      counter9: "Counter 9",
      counter10: "Counter 10",
      counter11: "Counter 11",
      counter12: "Counter 12",
      
      // Date Labels
      day: "Day",
      days: "days",
      today: "Today",
      thisMonth: "This Month",
      lastMonth: "Last Month",
      
      // New Analytics Charts & Features
      hourlyProductionPattern: "Hourly Production Pattern",
      topBottomProducts: "Top & Bottom Products",
      defectRateByHour: "Defect Rate by Hour",
      totalDefectsPerFactory: "Total Defects per Factory",
      top5DefectsPerFactory: "Top 5 Defects per Factory",
      workerQualityLeaderboard: "Worker Quality Leaderboard",
      equipmentPerformance: "Equipment Performance",
      factoryPerformanceComparison: "Factory Performance Comparison",
      
      // New KPI Cards
      firstPassYield: "First Pass Yield",
      peakProductionHour: "Peak Production Hour",
      mostProducedPart: "Most Produced Part",
      equipmentCount: "Equipment Count",
      
      // Modal and UI Elements
      defectDetails: "Defect Details",
      serial: "Serial",
      loadingDetailedRecords: "Loading detailed records...",
      showingRecords: "Showing",
      records: "records",
      record: "record",
      noDetailedRecordsFound: "No detailed records found",
      errorLoadingDetails: "Error loading details",
      clickToSort: "Click to sort by",
      close: "Close",
      
      // Table Headers (Dynamic)
      date: "Date",
      factory: "Factory",
      partNumber: "Part Number", 
      serialNumber: "Serial Number",
      workerName: "Worker Name",
      equipment: "Equipment",
      processQuantity: "Process Quantity",
      totalNG: "Total NG",
      cycleTime: "Cycle Time",
      counter: "Counter",
      units: "units",
      
      // Chart Data Labels
      productionVolume: "Production Volume",
      defectCount: "Defect Count",
      hourOfDay: "Hour of Day",
      defectRatePercentage: "Defect Rate (%)",
      efficiency: "Efficiency",
      downtime: "Downtime",
      utilization: "Utilization",
      topProducts: "Top Products",
      bottomProducts: "Bottom Products",
      mostProduced: "Most Produced",
      leastProduced: "Least Produced",
      
      // Status Messages
      noDefectPartsDataAvailable: "No defect parts data available for the selected period",
      loadingDefectPartsData: "Loading defect parts data...",
      errorLoadingDefectParts: "Error loading defect parts data",
      noDataAvailable: "No data available",
      
      // Time and Measurements
      hours: "hours",
      hour: "hour",
      am: "AM",
      pm: "PM",
      pieces: "pieces",
      rate: "rate",
      average: "average",
      maximum: "maximum",
      minimum: "minimum",
      
      // SCNA Work Order
      scna: "SCNA",
      scnaTitle: "SCNA Management",
      scnaSubtitle: "Supply Chain Network Analytics & Work Order Management",
      workOrder: "Work Order",
      workOrderTitle: "SCNA Work Order Management",
      workOrderSubtitle: "Manage SCNA Work Orders & Track Progress",
      workOrdersList: "Work Orders List",
      workOrderDetails: "Work Order Details",
      workOrderNumber: "Work Order Number",
      customer: "Customer",
      assignedTo: "Assigned To",
      estimatedCost: "Estimated Cost",
      deadline: "Deadline",
      materialLoading: "Material Loading",
      finishedGoods: "Finished Goods",
      quantityStatus: "Quantity Status",
      timeTrack: "Time Track",
      productSKU: "Product SKU",
      createdDate: "Created Date",
      owner: "Owner",
      allStatuses: "All Statuses",
      allCustomers: "All Customers",
      allAssignees: "All Assignees",
      dateFrom: "Deadline From",
      dateTo: "Deadline To",
      applyFilters: "Apply Filters",
      totalOrders: "Total Orders",
      inProgress: "In Progress",
      completed: "Completed",
      overdue: "Overdue",
      entered: "Entered",
      cancelled: "Cancelled",
      dueSoon: "Due Soon",
      itemsPerPage: "Items per page",

      // Inventory Management
      noInventoryItemsFound: "No inventory items found matching your criteria.",
      physicalStock: "Physical Stock",
      reservedStock: "Reserved Stock",
      availableStock: "Available Stock",
      viewTransactions: "View Transactions",
      noItemsToDisplay: "No items to display",
      loadingInventory: "Loading inventory...",
      allPartNumbers: "All Part Numbers",
      allBackNumbers: "All Back Numbers",
      loadingTransactions: "Loading transactions...",
      noTransactionsFound: "No transactions found",
      currentState: "Current State",
      transactionHistory: "Transaction History",
      dateTime: "Date/Time",
      action: "Action",
      physical: "Physical",
      reserved: "Reserved",
      available: "Available",
      source: "Source",
      note: "Note",
      system: "System",
      autoFilled: "auto-filled",
      partNumberRequired: "Part Number is required",
      serialNumberRequired: "Serial Number is required",
      quantityMustBePositive: "Quantity must be greater than 0",
      successfullyAdded: "Successfully added",
      units: "units",
      errorAddingInventory: "Error adding inventory",
      noDataToExport: "No data to export",

      // NODA Warehouse Management
      noPickingRequestsFound: "No picking requests found matching your criteria.",
      requestNumber: "Request #",
      type: "Type",
      autoGenerated: "Auto-generated",
      sufficient: "Sufficient",
      insufficient: "Insufficient",
      availableQuantity: "Available",
      inventoryErrorItemNotFound: "Inventory Error: Item not found in database",
      errorCheckingInventory: "Error checking inventory",
      errorCreatingRequest: "Error creating request",
      errorExportingData: "Error exporting data",
      errorLoadingDetails: "Error loading request details",
      pleaseCompleteAllFields: "Please fill in all fields",
      requestUpdatedSuccessfully: "Request updated successfully!",
      errorUpdatingRequest: "Error updating request",
      requestDeletedSuccessfully: "Request deleted successfully!",
      errorDeletingRequest: "Error deleting request",
      itemNotFoundInInventory: "Item not found in inventory",
      noItemsInCart: "No items in cart",
      pleaseAddAtLeastOneItem: "Please add at least one item to the cart",
      pleaseSelectPickupDate: "Please select a pickup date",
      checkingInventory: "Checking inventory...",
      errorSubmittingBulkRequest: "Error submitting bulk request",
      noItemsInEditCart: "No items in edit cart to add",
      errorAddingItemsToRequest: "Error adding items to request",
      pleaseSelectCSVFile: "Please select a CSV file",
      csvFileIsEmpty: "CSV file is empty",
      invalidCSVFormat: "Invalid CSV format. Header must contain either 品番 or 背番号",
      errorParsingCSVFile: "Error parsing CSV file",

      // Factories & Sensors
      loadingSensorHistory: "Loading sensor history...",
      noHistoricalData: "No sensor data in the last 30 days",
      noSensorData: "No sensor data",
      dateRange: "Date Range",
      factory: "Factory",
      itemsPerPage: "Items per page",
      sensorHistory: "Sensor History",
      allSensors: "All Sensors",
      loadingSensorData: "Loading sensor data...",
      failedToLoadImage: "Failed to load image",
      loadingFactories: "Loading factories...",
      total: "Total",
      totalNG: "Total NG",
      defectRate: "Defect Rate",
      environmentalData: "Environmental Data",
      clickToViewDetails: "Click to view factory details",
      loadingDataForFactory: "Loading data for",
      failedToLoadDataForFactory: "Failed to load data for",
      clickToAdd: "Click to add",
      process: "Process",
      topDefectiveProducts: "Top 15 Defective Products",
      defectRatePerProcess: "Defect Rate per Process",
      cycleTimePerProcess: "Cycle Time per Process",
      loadingDailyData: "Loading daily data...",
      failedToLoadDailyData: "Failed to load daily data",
      dataLoadError: "Error loading data. Please check console.",
      psaProcessDetails: "PSA Process Details",
      materialRequestDatabase: "Material Request Database Record",
      psaDataLoadError: "Error loading PSA data. Please check console.",
      updatedSuccessfully: "Updated successfully.",
      updateFailed: "Update failed.",
      loadingProductionData: "Loading production data...",
      production: "Production",
      totalWorkHours: "Total Work Hours",
      averageWorkHours: "Average Work Hours",

      // User Management
      failedToLoadUsers: "Failed to load users",
      firstName: "First Name",
      lastName: "Last Name",
      email: "Email",
      username: "Username",
      role: "Role",
      factory: "Factory",
      actions: "Actions",
      addFactory: "Add Factory",
      edit: "Edit",
      resetPassword: "Reset Password",
      delete: "Delete",

      // Master DB
      noFileSelected: "No file selected",
      csvParsingError: "CSV parsing error",
      csvPreviewTitle: "Preview (first 5 rows):",
      insertAllToDatabase: "Insert All to DB",
      noDataToInsert: "No data to insert",
      insertSuccessMessage: "Success: {successCount} inserted\nFailed: {failCount}",
      close: "Close",
      details: "Details",
      productImage: "Product Image",
      noImageUploaded: "No image uploaded.",
      updateImage: "Update Image",
      uploadImage: "Upload Image",
      ok: "OK",
      cancel: "Cancel",
      updatedSuccessfully: "Updated successfully.",
      updateFailed: "Update failed.",
      imageUploadedSuccessfully: "Image uploaded successfully.",
      imageUploadFailed: "Image upload failed.",
      uploadFailed: "Upload failed.",

      // Equipment
      errorLoadingEquipmentData: "Error loading equipment data",
      pleaseCheckConnection: "Please check your connection and try again.",
      retry: "Retry",
      all: "All",
      none: "None",
      errorApplyingFilters: "Error applying filters. Please try again.",
      noDataAvailable: "No data available for the selected filters.",
      tryAdjustingFilters: "Try adjusting your date range or equipment selection.",

      // SCNA Work Order
      loadingWorkOrders: "Loading work orders...",
      error: "Error",
      retry: "Retry",
      allCustomers: "All Customers",
      allAssignees: "All Assignees",

      // Freya Tablet
      failedToLoadProductionRecords: "Failed to load production records",

      // SCNA Machine Analytics
      pleaseSelectAtLeastOneMachine: "Please select at least one machine to view the analytics",
      loadingMachineAnalytics: "Loading machine analytics...",
      errorLoadingMachineData: "Error loading machine data",
      productionInformation: "Production Information",
      productionStats: "Production Stats",
      ngAnalysis: "NG Analysis",
      workOrderInformation: "Work Order Information",
      breakTimeInformation: "Break Time Information",
      qualityCheckInformation: "Quality Check Information",
      checkNumber: "Check",
      images: "Images",
      failedToLoadImage: "Failed to load image",

      // Analytics
      allFactories: "All Factories",
      pleaseSelectDates: "Please select both from and to dates",
      fromDateCannotBeLater: "From date cannot be later than to date",
      noDataAvailable: "No data available for the selected date range",

      // Approvals
      loadingFactories: "Loading factories...",
      errorLoadingFactories: "Error loading factories",

      // Status Display (for display purposes only - actual values stay in English)
      statusPending: "Pending",
      statusApproved: "Approved",
      statusRejected: "Rejected",
      statusEntered: "Entered",
      statusCancelled: "Cancelled",
      statusCompleted: "Completed",
      statusOverdue: "Overdue",
      statusInProgress: "In Progress",
      statusDueSoon: "Due Soon",

      // Action Display (for display purposes only)
      actionAdd: "Add",
      actionRemove: "Remove",
      actionReserve: "Reserve",
      actionRelease: "Release",
      actionUpdate: "Update",
      actionDelete: "Delete",
      actionEdit: "Edit",
      actionView: "View",
      actionExport: "Export",
      actionImport: "Import",

      // Additional common UI elements
      done: "Done",
      pickupDate: "Pickup Date",
      requestDate: "Request Date",
      requestedBy: "Requested By",
      lineItems: "Line Items",
      quantity: "Quantity",
      remarks: "Remarks",
      addToCart: "Add to Cart",
      clearCart: "Clear Cart",
      submitRequest: "Submit Request",
      bulkRequest: "Bulk Request",
      singleRequest: "Single Request",
      editMode: "Edit Mode",
      viewMode: "View Mode",
      addMoreItems: "Add More Items",
      markAsCompleted: "Mark as Completed",
      confirmDelete: "Are you sure you want to delete this?",
      confirmAction: "Are you sure?",

      // Additional NODA/Inventory UI Elements
      uploadCSV: "Upload CSV",
      csvExport: "CSV Export",
      newRequest: "New Request",
      pickingRequest: "Picking Request",
      totalItems: "Total Items",
      statusPending: "Pending",
      statusActive: "Active",
      statusComplete: "Completed",
      statusFailed: "Failed",
      statusUnknown: "Unknown",
      statusInProgress: "In Progress",
      statusValid: "Valid",
      statusInvalid: "Invalid",
      bulkRequest: "Bulk Request",
      singleRequest: "Single Request",
      items: "items",
      done: "done",
      qty: "Qty",
      qtyLabel: "Qty:",
      clickRowToView: "Click row to view",
      loadingRequests: "Loading requests...",
      retry: "Retry",
      allPartNumbers: "All Part Numbers",
      allBackNumbers: "All Back Numbers",
      partNumberRequired: "Part number is required",
      backNumberRequired: "Back number is required",
      validQuantityRequired: "Valid quantity is required",
      pickupDateRequired: "Pickup date is required",
      inventoryErrorItemNotFoundDB: "Inventory Error: Item not found in inventory database",
      insufficientInventory: "Insufficient Inventory!",
      creating: "Creating...",
      requestCreatedSuccessfully: "Request Created Successfully!",
      errorCreatingRequest: "Error creating request:",
      pleaseSelectValidCSV: "Please select a valid CSV file",
      csvMustContainHeader: "CSV file must contain header and at least one data row",
      invalidCSVFormatHeaders: "Invalid CSV format. Expected headers: 日付,背番号,収容数 or 日付,品番,収容数",
      noValidDataRows: "No valid data rows found in CSV",
      invalidCSVMultipleDates: "Invalid CSV: Multiple dates detected... All items in a picking order must have the same date.",
      notFound: "Not found",
      noInventory: "No inventory",
      invalid: "Invalid",
      csvUploadReview: "CSV Upload Review",
      reviewParsedData: "Review the parsed data before creating bulk request",
      formatDetected: "Format Detected:",
      pickupDate: "Pickup Date:",
      totalItems: "Total Items:",
      row: "Row",
      quantity: "Quantity",
      available: "Available",
      status: "Status",
      cancel: "Cancel",
      createBulkRequest: "Create Bulk Request",
      noValidItemsToSubmit: "No valid items to submit",
      successfullyCreatedBulkRequest: "Successfully created bulk request:",
      errorCreatingBulkRequest: "Error creating bulk request:",
      errorSubmittingBulkRequest: "Error submitting bulk request:",
      errorExportingData: "Error exporting data:",
      requestNumber: "Request Number",
      createdAt: "Created At",
      requestType: "Type",
      overallStatus: "Overall Status",
      createdBy: "Created By",
      unknown: "Unknown",
      existingItems: "Existing Items",
      addMoreItems: "Add More Items",
      lineItems: "Line Items",
      lineNumber: "Line #",
      actions: "Actions",
      esp32Only: "ESP32 Only",
      onlyESP32CanComplete: "Only ESP32 can complete in-progress items",
      complete: "Complete",
      noLineItemsFound: "No line items found",
      addMoreItemsHeader: "Add More Items",
      addMoreItemsInstruction: "You can add more items to this picking request. Items will be added to the same pickup date",
      addSingleItem: "Add Single Item",
      addIndividualItems: "Add individual items one by one",
      addItem: "Add Item",
      uploadCSV: "Upload CSV",
      bulkAddFromCSV: "Bulk add items from CSV file",
      addSingleItemForm: "Add Single Item",
      itemsToAdd: "Items to Add",
      clearAll: "Clear All",
      addAllItems: "Add All Items",
      close: "Close",
      saveChanges: "Save Changes",
      pleaseCompleteAllFields: "Please fill in all fields",
      quantityMustBePositive: "Quantity must be greater than 0",
      requestUpdatedSuccessfully: "Request updated successfully!",
      errorUpdatingRequest: "Error updating request:",
      confirmDeleteRequest: "Are you sure you want to delete this request?",
      requestDeletedSuccessfully: "Request deleted successfully!",
      errorDeletingRequest: "Error deleting request:",
      itemAlreadyInCart: "Item already exists in cart. Do you want to update the quantity?",
      itemNotFoundInInventory: "Item not found in inventory",
      insufficientInventoryAvailable: "Insufficient inventory. Available:",
      requested: "Requested:",
      errorCheckingInventoryTryAgain: "Error checking inventory. Please try again.",
      itemAddedToCart: "Item added to cart successfully!",
      confirmRemoveFromCart: "Are you sure you want to remove from the cart?",
      itemRemovedFromCart: "Item removed from cart",
      noItemsInCart: "No items in cart",
      qtyShort: "Qty:",
      availableShort: "Available:",
      pleaseAddAtLeastOneItem: "Please add at least one item to the cart",
      pleaseSelectPickupDate: "Please select a pickup date",
      checkingInventory: "Checking inventory...",
      insufficientStock: "Insufficient Stock",
      errorCheckingInventory: "Error checking inventory",
      bulkRequestSubmittedSuccessfully: "Bulk request submitted successfully!",
      itemAlreadyInEditCart: "Item already exists in edit cart. Do you want to update the quantity?",
      itemAddedToEditCart: "Item added to edit cart!",
      confirmRemoveFromEditCart: "Remove from edit cart?",
      itemRemovedFromEditCart: "Item removed from edit cart",
      confirmClearEditCart: "Clear all items from edit cart?",
      editCartCleared: "Edit cart cleared",
      partNumberBackNumberNotFound: "Part number and back number combination not found in master database",
      errorValidatingMasterData: "Error validating master data",
      physicalStockCSV: "Physical Stock",
      reservedStockCSV: "Reserved Stock",
      availableStockCSV: "Available Stock",
      lastUpdatedCSV: "Last Updated",

      // Inventory Tab Specific
      inventoryTitle: "Inventory Management",
      inventorySubtitle: "Two-Stage Inventory Tracking System",
      addInventory: "Add Inventory",
      inventoryItems: "Inventory Items",
      inventoryTransactions: "Inventory Transactions",
      totalItems: "Total Items",
      physicalStock: "Physical Stock",
      reservedStock: "Reserved Stock",
      availableStock: "Available Stock",
      quantityToAdd: "Quantity to Add",
      searchInventory: "Search inventory...",
      itemsPerPage: "Items per page",
      
      // NODA Tab Specific
      nodaTitle: "NODA Warehouse Management",
      nodaSubtitle: "Warehouse Picking Order Management System",
      pickingRequests: "Picking Requests",
      pickingRequestDetails: "Picking Request Details",
      bulkPickingRequest: "Bulk Picking Request",
      addItems: "Add Items",
      reviewCart: "Review Cart",
      submit: "Submit",
      pickupDateAllItems: "Pickup Date (All Items)",
      addItemToCart: "Add Item to Cart",
      enterPartNumber: "Enter part number",
      enterBackNumber: "Enter back number",
      qtyPlaceholder: "Qty",
      cartItems: "Cart Items",
      proceedToReview: "Review Cart",
      backToAddItems: "Back to Add Items",
      proceedToSubmit: "Proceed to Submit",
      readyToSubmit: "Ready to Submit",
      bulkPickingRequestReady: "Your bulk picking request is ready to be submitted.",
      submittingBulkRequest: "Submitting bulk request...",
      backToReview: "Back to Review",
      submitBulkRequest: "Submit Bulk Request",
      itemsToRequest: "Items to Request",
      searchRequests: "Search requests...",
      allStatuses: "All Statuses",
      
      // Alert Messages for NODA
      alertInventoryError: "Inventory Error: Item not found in inventory database.\n\nPlease check the back number and try again.",
      alertInsufficientInventory: "Insufficient Inventory!",
      alertRequested: "Requested:",
      alertAvailable: "Available:",
      alertReduceQuantity: "Please reduce the quantity or check inventory levels.",
      alertErrorCheckingInventory: "Error checking inventory: ",
      alertRequestCreatedSuccess: "Request Created Successfully!",
      alertRequestNumber: "Request Number:",
      alertErrorCreatingRequest: "Error creating request: ",
      alertErrorExportingData: "Error exporting data: ",
      alertNoDataToExport: "No data to export",
      alertErrorLoadingRequestDetails: "Error loading request details: ",
      alertFillAllFields: "Please fill in all fields",
      alertQuantityGreaterThanZero: "Quantity must be greater than 0",
      alertItemExistsInCart: "Item {backNumber} already exists in cart. Do you want to update the quantity?",
      alertItemNotFoundInInventory: "Item not found in inventory",
      alertErrorCheckingInventoryTryAgain: "Error checking inventory. Please try again.",
      alertItemAddedToCart: "Item {backNumber} added to cart successfully!",
      alertAddAtLeastOneItem: "Please add at least one item to the cart",
      alertSelectPickupDate: "Please select a pickup date",
      alertNoItemsToSubmit: "No items in cart to submit",
      alertBulkRequestSubmitted: "Bulk request submitted successfully!",
      alertProcessedItems: "Processed Items:",
      alertFailedItems: "Failed Items:",
      alertFailedSubmitBulkRequest: "Failed to submit bulk request",
      alertErrorSubmittingBulkRequest: "Error submitting bulk request: ",
      alertRequestUpdatedSuccess: "Request updated successfully!",
      alertErrorUpdatingRequest: "Error updating request: ",
      alertRequestDeletedSuccess: "Request deleted successfully!",
      alertErrorDeletingRequest: "Error deleting request: ",
      alertConfirmDeleteRequest: "Are you sure you want to delete this request?",
      alertConfirmRemoveFromCart: "Are you sure you want to remove {backNumber} from the cart?",
      alertItemRemovedFromCart: "Item {backNumber} removed from cart",
      alertErrorUpdatingLineItem: "Error updating line item status: ",
      alertMarkLineItemCompleted: "Mark line item {lineNumber} as completed?",
      alertItemExistsInEditCart: "Item {backNumber} already exists in edit cart. Do you want to update the quantity?",
      alertNoItemsInEditCart: "No items in edit cart to add",
      alertItemsAddedSuccess: "Items added successfully!",
      alertAddedItems: "Added Items:",
      alertFailedAddItems: "Failed to add items to request",
      alertErrorAddingItems: "Error adding items to request: ",
      alertSelectCsvFile: "Please select a CSV file",
      alertCsvFileEmpty: "CSV file is empty",
      alertInvalidCsvFormat: "Invalid CSV format. Header must contain either 品番 or 背番号",
      alertCsvProcessed: "CSV processed: {success} items added, {failed} failed",
      alertErrorParsingCsv: "Error parsing CSV file: ",
      alertConfirmRemoveFromEditCart: "Remove {backNumber} from edit cart?",
      alertItemRemovedFromEditCart: "Item {backNumber} removed from edit cart",
      alertConfirmClearEditCart: "Clear all items from edit cart?",
      alertEditCartCleared: "Edit cart cleared",
      unknownError: "Unknown error",

    },
    ja: {
      // Navigation
      dashboard: "ダッシュボード",
      factories: "工場一覧",
      processes: "工程",
      notifications: "通知",
      analytics: "分析",
      userManagement: "ユーザー管理",
      approvals: "承認",
      masterDB: "マスター製品",
      customerManagement: "顧客管理",
      equipment: "設備",
      
      // Common
      searchPlaceholder: "検索...",
      loading: "読み込み中...",
      logout: "ログアウト",
      role: "役職",
      submit: "送信",
      cancel: "キャンセル",
      delete: "削除",
      edit: "編集",
      save: "保存",
      refresh: "更新",
      export: "エクスポート",
      import: "インポート",
      upload: "アップロード",
      download: "ダウンロード",
      view: "表示",
      add: "追加",
      create: "作成",
      update: "更新",
      filter: "フィルター",
      search: "検索",
      all: "すべて",
      total: "合計",
      
      // Login Page
      loginTitle: "ログイン",
      username: "ユーザー名",
      password: "パスワード",
      enterUsername: "ユーザー名を入力",
      enterPassword: "パスワードを入力",
      invalidCredentials: "認証情報が無効です",
      loginFailed: "ログインに失敗しました",
      networkError: "ネットワークエラー",
      
      // Dashboard
      factoryOverview: "工場概要",
      viewDetails: "工場の詳細を表示",
      
      // Analytics
      defectRateAnalytics: "不良率分析",
      monthlySummary: "月次サマリー",
      
      // Factories
      factoryListTitle: "工場リスト",
      
      // User Management
      userManagementTitle: "ユーザー管理",
      searchUsers: "ユーザーを検索...",
      createNewUser: "新しいユーザーを作成",
      firstName: "名",
      lastName: "姓",
      email: "メールアドレス",
      selectRole: "役職を選択",
      factorySelection: "工場選択",
      loadingUsers: "ユーザーを読み込み中...",
      accessDenied: "アクセス拒否",
      
      // Approvals
      approvalsTitle: "データ承認システム",
      kensa: "検査 (Kensa)",
      press: "プレス (Press)",
      slit: "スリット (Slit)",
      pending: "保留中",
      hanchoApproved: "班長承認済み",
      fullyApproved: "完全承認済み",
      rejected: "却下",
      pendingApproval: "班長承認待ち",
      waitingKacho: "課長承認待ち",
      correctionNeeded: "修正要求",
      kachoRequest: "課長修正要求",
      todayTotal: "今日の総数",
      submittedToday: "本日提出分",
      needsCorrection: "要修正・再提出",
      hanchoAction: "班長対応必要",
      kachoApprovalComplete: "課長承認完了",
      currentDateOnly: "現在の日付のみ",
      allHistoricalData: "全履歴データ",
      showingCurrentDate: "現在の日付データを表示中",
      showingAllData: "全履歴データを表示中",
      
      // Master DB
      masterProductManagement: "Master 製品管理",
      csvFile: "CSVファイル",
      uploadPreview: "アップロード & プレビュー",
      factory: "工場",
      rl: "R/L",
      color: "色",
      processEquipment: "加工設備",
      searchPlaceholderMaster: "品番、モデル、背番号、品名で検索...",
      totalCount: "総件数",
      withImages: "画像あり",
      noImages: "画像なし",
      recentlyAdded: "最近追加",
      partNumber: "品番",
      serialNumber: "背番号",
      model: "モデル",
      productName: "品名",
      defectRate: "不良率",
      exportCSV: "CSVでエクスポート",
      exportPDF: "PDFでエクスポート",
      addNewRecord: "新規レコード追加",
      addNewRecordModal: "新規レコード追加",
      productImage: "製品画像",
      noImageAvailable: "画像がありません",
      uploadImage: "画像をアップロード",
      cancel: "キャンセル",
      save: "保存",
      pleaseEnterAtLeastOneField: "少なくとも1つのフィールドに入力してください。",
      recordAddedSuccessfully: "新規レコードが正常に追加されました！",
      failedToAddRecord: "レコードの追加に失敗しました: ",
      
      // Equipment
      equipmentTitle: "設備管理",
      equipmentFilter: "設備フィルター（工場別）",
      dateRange: "期間指定",
      applyFilters: "フィルターを適用",
      exportPDF: "PDFエクスポート",
      totalShots: "総ショット数",
      avgShotsDay: "平均ショット/日",
      avgShotsHour: "平均ショット/時間",
      workingHoursDay: "実働時間/日",
      dailyPerformanceTrend: "日次パフォーマンストレンド",
      shots: "ショット",
      workingHours: "実働時間",
      processQty: "加工数",
      defects: "不良数",
      date: "日付",
      worker: "作業者",
      time: "時間",
      entries: "件",
      records: "レコード",
      show: "表示",
      noDataAvailable: "選択されたフィルターにデータがありません",
      tryAdjustingFilters: "期間や設備の選択を調整してください",
      
      // Dashboard/Factories metrics
      totalNG: "総不良数",
      normal: "正常",
      warning: "警告",
      highDefectRate: "高不良率",
      status: "ステータス",
      
      // Customer Management
      customerManagementTitle: "顧客管理",
      
      // Processes
      processesTitle: "工程",
      
      // Notifications
      notificationsTitle: "通知",
      
      // Master User Admin Panel
      masterUserAdminPanel: "マスターユーザー管理パネル",
      searchByUsernameCompanyEmail: "ユーザー名、会社名、またはメールアドレスで検索...",
      createMasterUser: "マスターユーザーを作成",
      companyName: "会社名",
      databaseName: "データベース名",
      devicesOptional: "デバイス (オプション)",
      addDevice: "+ デバイスを追加",
      validUntil: "有効期限",
      database: "データベース",
      devices: "デバイス",
      actions: "アクション",
      resetPassword: "パスワードリセット",
      
      // Page titles
      dashboardTitle: "ダッシュボード",
      factoriesTitle: "工場一覧",
      processesTitle: "工程",
      notificationsTitle: "通知",
      analyticsTitle: "分析",
      approvalsTitle: "承認",
      customerManagementTitle: "顧客管理",
      
      // Approval View Modes
      tableView: "テーブルビュー（個別承認）",
      listView: "リストビュー（一括承認）",
      viewMode: "表示モード:",
      batchApproveSelected: "選択項目を一括承認",
      batchRejectSelected: "選択項目を一括却下",
      selected: "選択中",
      dataUpdate: "🔄 データ更新",
      allFactories: "全工場",
      allStatus: "全ステータス",
      
      // Analytics
      analytics: "分析",
      analyticsInsights: "検査データの詳細分析とインサイト",
      totalProduction: "総生産量",
      totalDefects: "総不良数",
      avgDefectRate: "平均不良率",
      totalFactories: "工場数",
      totalWorkers: "作業者数",
      avgCycleTime: "平均サイクルタイム",
      productionTrend: "生産量・不良数の推移",
      qualityTrend: "品質トレンド（不良率推移）",
      factoryComparison: "工場別生産量・不良率比較",
      defectDistribution: "不良分布（カウンター別）",
      workerPerformance: "作業者別パフォーマンス（上位10名）",
      processEfficiency: "設備別効率（平均サイクルタイム）",
      dateRange: "期間",
      fromDate: "開始日",
      toDate: "終了日",
      today: "今日",
      last7Days: "過去7日間",
      last30Days: "過去30日間",
      last90Days: "過去90日間",
      thisMonth: "今月",
      lastMonth: "先月",
      customRange: "カスタム",
      exportCsv: "CSV出力",
      refresh: "更新",
      loadingAnalytics: "分析データを読み込み中...",
      noDataAvailable: "選択された期間にデータがありません",
      processFilter: "プロセス",
      allProcesses: "全プロセス",
      inspectionProcess: "検査 (kensaDB)",
      pressProcess: "プレス (pressDB)",
      slitProcess: "スリット (slitDB)",
      srsProcess: "SRS (SRSDB)",
      
      // Additional common terms
      none: "なし",
      selectAll: "全て選択",
      deselectAll: "全て解除",
      loading: "読み込み中...",
      loadingData: "データを読み込み中...",
      loadingFactories: "工場データを読み込み中...",
      pleaseWait: "最新情報を取得中です。しばらくお待ちください",
      error: "エラー",
      success: "成功",
      warning: "警告",
      information: "情報",
      confirmation: "確認",
      yes: "はい",
      no: "いいえ",
      ok: "OK",
      close: "閉じる",
      back: "戻る",
      next: "次へ",
      previous: "前へ",
      page: "ページ",
      of: "の",
      first: "最初",
      last: "最後",
      
      // Environmental Data
      environmentalData: "環境データ",
      temperature: "温度",
      humidity: "湿度",
      co2: "CO2",
      co2Level: "CO2濃度",
      updateData: "データ更新",
      lastUpdated: "最終更新",
      simulatedData: "※ 模擬データ",
      refreshEnvironmentalData: "環境データを更新",
      normalRange: "適正範囲",
      temperatureRange: "18-26°C",
      humidityRange: "40-60%",
      co2Standard: "<1000ppm",
      ventilationRequired: "換気必要",
      ventilationRecommended: "換気推奨",
      good: "良好",
      lowTemperatureWarning: "低温注意",
      highTemperatureWarning: "高温注意", 
      lowTemperatureAlert: "低温警告",
      highTemperatureAlert: "高温警告",
      dryAlert: "乾燥警告",
      highHumidityAlert: "高湿度警告",
      dryWarning: "乾燥注意",
      highHumidityWarning: "高湿度注意",
      
      // Physical Sensors
      physicalSensors: "物理センサー",
      sensors: "センサー",
      sensorCount: "台",
      highestTemp: "最高温度",
      averageHumidity: "平均湿度",
      viewDetails: "詳細表示",
      lastUpdate: "最終更新",
      sensorHistory: "センサー履歴",
      temperatureHistory: "温度履歴",
      noDataLast30Days: "過去30日間にセンサーデータがありません",
      records: "件",
      latestTemperature: "最新温度", 
      clickForHistory: "クリックして詳細履歴表示",
      last30Days: "過去30日間のセンサーデータ",
      noSensorData: "センサーデータなし",
      allSensors: "全センサー",
      sensorDetails: "センサー詳細",
      activeSensors: "アクティブセンサー",
      sensor: "センサー",
      loadingSensorData: "センサーデータを読み込み中...",
      failedToLoad: "データの読み込みに失敗しました",
      items: "件中",
      previous: "前へ",
      next: "次へ",
      dataUpdatesEvery15Min: "センサーデータは15分間隔で更新されます",
      
      // WBGT (湿球黒球温度)
      wbgt: "WBGT",
      extremeHeat: "極度高温",
      dangerousHeat: "高温危険",
      heatCaution: "高温注意", 
      safe: "安全",
      
      // Analytics Page
      analyticsTitle: "分析",
      analyticsSubtitle: "検査データの詳細分析とインサイト",
      periodSelection: "期間選択",
      last30Days: "過去30日間",
      last7Days: "過去7日間",
      last3Months: "過去3ヶ月",
      customRange: "カスタム範囲",
      startDate: "開始日",
      endDate: "終了日",
      process: "プロセス",
      inspection: "検査 (kensaDB)",
      press: "プレス (pressDB)",
      slit: "スリット (slitDB)",
      srs: "SRS (SRSDB)",
      factoryFilter: "工場フィルター",
      allFactories: "全工場",
      csvExport: "CSV出力",
      update: "更新",
      
      // Analytics KPI Cards
      totalProduction: "総生産量",
      totalDefects: "総不良数",
      defectRate: "不良率",
      factoryCount: "工場数",
      workerCount: "作業者数",
      avgCycleTime: "平均サイクルタイム",
      minutes: "分",
      
      // Analytics Charts
      productionDefectTrend: "生産量・不良数の推移",
      production: "生産量",
      defects: "不良数",
      qualityTrendDefectRate: "品質トレンド (不良率推移)",
      defectRatePercent: "不良率 (%)",
      factoryPerformance: "工場別パフォーマンス",
      workerPerformance: "作業者別パフォーマンス (上位10名)",
      equipmentEfficiency: "設備別効率 (上位10名)",
      equipment: "設備",
      cycleTime: "サイクルタイム",
      defectDistributionByProcess: "不良分布 (プロセス別)",
      temperatureTrend: "温度トレンド",
      temperature: "温度",
      celsius: "°C",
      humidityTrend: "湿度トレンド",
      humidity: "湿度",
      percent: "%",
      
      // Chart Labels
      counter1: "カウンター1",
      counter2: "カウンター2", 
      counter3: "カウンター3",
      counter4: "カウンター4",
      counter5: "カウンター5",
      counter6: "カウンター6",
      counter7: "カウンター7",
      counter8: "カウンター8",
      counter9: "カウンター9",
      counter10: "カウンター10",
      counter11: "カウンター11",
      counter12: "カウンター12",
      
      // Date Labels
      day: "日",
      days: "日間",
      today: "今日",
      thisMonth: "今月",
      lastMonth: "先月",
      
      // New Analytics Charts & Features
      hourlyProductionPattern: "時間別生産パターン",
      topBottomProducts: "上位・下位製品",
      defectRateByHour: "時間別不良率",
      totalDefectsPerFactory: "工場別総不良数",
      top5DefectsPerFactory: "工場別上位5不良部品",
      workerQualityLeaderboard: "作業者品質ランキング",
      equipmentPerformance: "設備パフォーマンス",
      factoryPerformanceComparison: "工場パフォーマンス比較",
      
      // New KPI Cards
      firstPassYield: "初回合格率",
      peakProductionHour: "生産ピーク時間",
      mostProducedPart: "最多生産部品",
      equipmentCount: "設備数",
      
      // Modal and UI Elements
      defectDetails: "不良詳細",
      serial: "シリアル",
      loadingDetailedRecords: "詳細記録を読み込み中...",
      showingRecords: "表示中",
      records: "件",
      record: "件",
      noDetailedRecordsFound: "詳細記録が見つかりません",
      errorLoadingDetails: "詳細の読み込みエラー",
      clickToSort: "クリックしてソート",
      close: "閉じる",
      
      // Table Headers (Dynamic)
      date: "日付",
      factory: "工場",
      partNumber: "品番", 
      serialNumber: "背番号",
      workerName: "作業者名",
      equipment: "設備",
      processQuantity: "加工数量",
      totalNG: "総不良数",
      cycleTime: "サイクルタイム",
      counter: "カウンター",
      units: "個",
      
      // Chart Data Labels
      productionVolume: "生産量",
      defectCount: "不良数",
      hourOfDay: "時刻",
      defectRatePercentage: "不良率 (%)",
      efficiency: "効率",
      downtime: "ダウンタイム",
      utilization: "稼働率",
      topProducts: "上位製品",
      bottomProducts: "下位製品",
      mostProduced: "最多生産",
      leastProduced: "最少生産",
      
      // Status Messages
      noDefectPartsDataAvailable: "選択期間の不良部品データがありません",
      loadingDefectPartsData: "不良部品データを読み込み中...",
      errorLoadingDefectParts: "不良部品データの読み込みエラー",
      noDataAvailable: "データがありません",
      
      // Time and Measurements
      hours: "時間",
      hour: "時",
      am: "午前",
      pm: "午後",
      pieces: "個",
      rate: "率",
      average: "平均",
      maximum: "最大",
      minimum: "最小",
      
      // SCNA Work Order
      scna: "SCNA",
      scnaTitle: "SCNA管理",
      scnaSubtitle: "サプライチェーンネットワーク分析とワークオーダー管理",
      workOrder: "ワークオーダー",
      workOrderTitle: "SCNAワークオーダー管理",
      workOrderSubtitle: "SCNAワークオーダーの管理と進捗追跡",
      workOrdersList: "ワークオーダー一覧",
      workOrderDetails: "ワークオーダー詳細",
      workOrderNumber: "ワークオーダー番号",
      customer: "顧客",
      assignedTo: "担当者",
      estimatedCost: "見積金額",
      deadline: "締切日",
      materialLoading: "材料投入",
      finishedGoods: "完成品",
      quantityStatus: "数量ステータス",
      timeTrack: "時間追跡",
      productSKU: "製品SKU",
      createdDate: "作成日",
      owner: "所有者",
      allStatuses: "全ステータス",
      allCustomers: "全顧客",
      allAssignees: "全担当者",
      dateFrom: "期限開始",
      dateTo: "期限終了",
      applyFilters: "フィルター適用",
      totalOrders: "総注文数",
      inProgress: "進行中",
      completed: "完了",
      overdue: "期限切れ",
      entered: "入力済み",
      cancelled: "キャンセル",
      dueSoon: "期限間近",
      itemsPerPage: "ページ当たりの項目数",

      // Inventory Management
      noInventoryItemsFound: "条件に一致する在庫アイテムが見つかりません。",
      physicalStock: "物理在庫",
      reservedStock: "予約済み在庫",
      availableStock: "利用可能在庫",
      viewTransactions: "トランザクションを表示",
      noItemsToDisplay: "表示するアイテムがありません",
      loadingInventory: "在庫を読み込み中...",
      allPartNumbers: "すべての品番",
      allBackNumbers: "すべての背番号",
      loadingTransactions: "トランザクションを読み込み中...",
      noTransactionsFound: "トランザクションが見つかりません",
      currentState: "現在の状態",
      transactionHistory: "トランザクション履歴",
      dateTime: "日付/時刻",
      action: "操作",
      physical: "物理",
      reserved: "予約済み",
      available: "利用可能",
      source: "ソース",
      note: "メモ",
      system: "システム",
      autoFilled: "自動入力",
      partNumberRequired: "品番は必須です",
      serialNumberRequired: "背番号は必須です",
      quantityMustBePositive: "数量は0より大きい必要があります",
      successfullyAdded: "正常に追加されました",
      units: "個",
      errorAddingInventory: "在庫追加エラー",
      noDataToExport: "エクスポートするデータがありません",

      // NODA Warehouse Management
      noPickingRequestsFound: "条件に一致するピッキングリクエストが見つかりません。",
      requestNumber: "リクエスト#",
      type: "タイプ",
      autoGenerated: "自動生成",
      sufficient: "十分",
      insufficient: "不足",
      availableQuantity: "利用可能",
      inventoryErrorItemNotFound: "在庫エラー: データベースにアイテムが見つかりません",
      errorCheckingInventory: "在庫確認エラー",
      errorCreatingRequest: "リクエスト作成エラー",
      errorExportingData: "データエクスポートエラー",
      errorLoadingDetails: "リクエスト詳細の読み込みエラー",
      pleaseCompleteAllFields: "すべてのフィールドに入力してください",
      requestUpdatedSuccessfully: "リクエストが正常に更新されました!",
      errorUpdatingRequest: "リクエスト更新エラー",
      requestDeletedSuccessfully: "リクエストが正常に削除されました!",
      errorDeletingRequest: "リクエスト削除エラー",
      itemNotFoundInInventory: "アイテムが在庫に見つかりません",
      noItemsInCart: "カートにアイテムがありません",
      pleaseAddAtLeastOneItem: "カートに少なくとも1つのアイテムを追加してください",
      pleaseSelectPickupDate: "ピックアップ日を選択してください",
      checkingInventory: "在庫を確認中...",
      errorSubmittingBulkRequest: "一括リクエスト送信エラー",
      noItemsInEditCart: "追加するアイテムが編集カートにありません",
      errorAddingItemsToRequest: "リクエストへのアイテム追加エラー",
      pleaseSelectCSVFile: "CSVファイルを選択してください",
      csvFileIsEmpty: "CSVファイルが空です",
      invalidCSVFormat: "無効なCSV形式です。ヘッダーは品番または背番号のいずれかを含む必要があります",
      errorParsingCSVFile: "CSVファイル解析エラー",

      // Factories & Sensors
      loadingSensorHistory: "センサー履歴を読み込み中...",
      noHistoricalData: "過去30日間にセンサーデータがありません",
      noSensorData: "センサーデータなし",
      dateRange: "期間指定",
      factory: "工場",
      itemsPerPage: "ページあたりのアイテム数",
      sensorHistory: "センサー履歴",
      allSensors: "全センサー",
      loadingSensorData: "センサーデータを読み込み中...",
      failedToLoadImage: "画像の読み込みに失敗しました",
      loadingFactories: "工場を読み込み中...",
      total: "合計",
      totalNG: "総不良数",
      defectRate: "不良率",
      environmentalData: "環境データ",
      clickToViewDetails: "工場の詳細を表示するには、クリックしてください",
      loadingDataForFactory: "データを読み込み中",
      failedToLoadDataForFactory: "データの読み込みに失敗しました",
      clickToAdd: "クリックして追加",
      process: "工程",
      topDefectiveProducts: "上位15の欠陥製品",
      defectRatePerProcess: "工程別不良率",
      cycleTimePerProcess: "工程別サイクルタイム",
      loadingDailyData: "日次データを読み込み中...",
      failedToLoadDailyData: "日次データの読み込みに失敗しました",
      dataLoadError: "データの読み込みエラー。コンソールを確認してください。",
      psaProcessDetails: "PSA工程の詳細",
      materialRequestDatabase: "材料リクエストデータベースレコード",
      psaDataLoadError: "PSAデータの読み込みエラー。コンソールを確認してください。",
      updatedSuccessfully: "正常に更新されました。",
      updateFailed: "更新に失敗しました。",
      loadingProductionData: "生産データを読み込み中...",
      production: "生産",
      totalWorkHours: "総作業時間",
      averageWorkHours: "平均作業時間",

      // User Management
      failedToLoadUsers: "ユーザーの読み込みに失敗しました",
      firstName: "名",
      lastName: "姓",
      email: "メールアドレス",
      username: "ユーザー名",
      role: "役職",
      factory: "工場",
      actions: "操作",
      addFactory: "工場を追加",
      edit: "編集",
      resetPassword: "パスワードリセット",
      delete: "削除",

      // Master DB
      noFileSelected: "ファイルが選択されていません",
      csvParsingError: "CSVパースエラー",
      csvPreviewTitle: "プレビュー（最初の5行）:",
      insertAllToDatabase: "すべてDBに挿入",
      noDataToInsert: "挿入するデータがありません",
      insertSuccessMessage: "成功: {successCount}件が挿入されました\n失敗: {failCount}件",
      close: "閉じる",
      details: "詳細",
      productImage: "製品画像",
      noImageUploaded: "画像がアップロードされていません。",
      updateImage: "画像を更新",
      uploadImage: "画像をアップロード",
      ok: "OK",
      cancel: "キャンセル",
      updatedSuccessfully: "正常に更新されました。",
      updateFailed: "更新に失敗しました。",
      imageUploadedSuccessfully: "画像が正常にアップロードされました。",
      imageUploadFailed: "画像のアップロードに失敗しました。",
      uploadFailed: "アップロードに失敗しました。",

      // Equipment
      errorLoadingEquipmentData: "設備データの読み込みエラー",
      pleaseCheckConnection: "接続を確認して、もう一度お試しください。",
      retry: "リトライ",
      all: "すべて",
      none: "なし",
      errorApplyingFilters: "フィルター適用エラー。もう一度お試しください。",
      noDataAvailable: "選択したフィルターに利用可能なデータがありません。",
      tryAdjustingFilters: "期間または設備の選択を調整してください。",

      // SCNA Work Order
      loadingWorkOrders: "ワークオーダーを読み込み中...",
      error: "エラー",
      retry: "リトライ",
      allCustomers: "全顧客",
      allAssignees: "全担当者",

      // Freya Tablet
      failedToLoadProductionRecords: "生産レコードの読み込みに失敗しました",

      // SCNA Machine Analytics
      pleaseSelectAtLeastOneMachine: "分析を表示するには、少なくとも1つの機械を選択してください",
      loadingMachineAnalytics: "機械分析を読み込み中...",
      errorLoadingMachineData: "機械データの読み込みエラー",
      productionInformation: "生産情報",
      productionStats: "生産統計",
      ngAnalysis: "NG分析",
      workOrderInformation: "ワークオーダー情報",
      breakTimeInformation: "休憩時間情報",
      qualityCheckInformation: "品質チェック情報",
      checkNumber: "チェック",
      images: "画像",
      failedToLoadImage: "画像の読み込みに失敗しました",

      // Analytics
      allFactories: "全工場",
      pleaseSelectDates: "開始日と終了日の両方を選択してください",
      fromDateCannotBeLater: "開始日は終了日より後にできません",
      noDataAvailable: "選択した日付範囲に利用可能なデータがありません",

      // Approvals
      loadingFactories: "工場を読み込み中...",
      errorLoadingFactories: "工場の読み込みエラー",

      // Status Display (表示用のみ - 実際の値は英語のまま)
      statusPending: "保留中",
      statusApproved: "承認済み",
      statusRejected: "却下",
      statusEntered: "入力済み",
      statusCancelled: "キャンセル",
      statusCompleted: "完了",
      statusOverdue: "期限切れ",
      statusInProgress: "進行中",
      statusDueSoon: "期限間近",

      // Action Display (表示用のみ)
      actionAdd: "追加",
      actionRemove: "削除",
      actionReserve: "予約",
      actionRelease: "解放",
      actionUpdate: "更新",
      actionDelete: "削除",
      actionEdit: "編集",
      actionView: "表示",
      actionExport: "エクスポート",
      actionImport: "インポート",

      // Additional common UI elements
      done: "完了",
      pickupDate: "ピックアップ日",
      requestDate: "リクエスト日",
      requestedBy: "依頼者",
      lineItems: "明細",
      quantity: "数量",
      remarks: "備考",
      addToCart: "カートに追加",
      clearCart: "カートをクリア",
      submitRequest: "リクエストを送信",
      bulkRequest: "一括リクエスト",
      singleRequest: "単一リクエスト",
      editMode: "編集モード",
      viewMode: "表示モード",
      addMoreItems: "さらにアイテムを追加",
      markAsCompleted: "完了としてマーク",
      confirmDelete: "本当に削除してもよろしいですか？",
      confirmAction: "よろしいですか？",

      // Additional NODA/Inventory UI Elements
      uploadCSV: "CSVをアップロード",
      csvExport: "CSVエクスポート",
      newRequest: "新規リクエスト",
      pickingRequest: "ピッキングリクエスト",
      totalItems: "総アイテム数",
      statusPending: "保留中",
      statusActive: "アクティブ",
      statusComplete: "完了",
      statusFailed: "失敗",
      statusUnknown: "不明",
      statusInProgress: "進行中",
      statusValid: "有効",
      statusInvalid: "無効",
      bulkRequest: "一括リクエスト",
      singleRequest: "単一リクエスト",
      items: "個",
      done: "完了",
      qty: "数量",
      qtyLabel: "数量:",
      clickRowToView: "行をクリックして表示",
      loadingRequests: "リクエストを読み込み中...",
      retry: "リトライ",
      allPartNumbers: "すべての品番",
      allBackNumbers: "すべての背番号",
      partNumberRequired: "品番は必須です",
      backNumberRequired: "背番号は必須です",
      validQuantityRequired: "有効な数量が必要です",
      pickupDateRequired: "ピックアップ日は必須です",
      inventoryErrorItemNotFoundDB: "在庫エラー: データベースにアイテムが見つかりません",
      insufficientInventory: "在庫不足!",
      creating: "作成中...",
      requestCreatedSuccessfully: "リクエストが正常に作成されました!",
      errorCreatingRequest: "リクエスト作成エラー:",
      pleaseSelectValidCSV: "有効なCSVファイルを選択してください",
      csvMustContainHeader: "CSVファイルにはヘッダーと少なくとも1行のデータが必要です",
      invalidCSVFormatHeaders: "無効なCSV形式です。期待されるヘッダー: 日付,背番号,収容数 または 日付,品番,収容数",
      noValidDataRows: "CSVに有効なデータ行が見つかりません",
      invalidCSVMultipleDates: "無効なCSV: 複数の日付が検出されました...ピッキングオーダーのすべてのアイテムは同じ日付である必要があります。",
      notFound: "見つかりません",
      noInventory: "在庫なし",
      invalid: "無効",
      csvUploadReview: "CSVアップロードレビュー",
      reviewParsedData: "一括リクエストを作成する前に解析データを確認してください",
      formatDetected: "検出された形式:",
      pickupDate: "ピックアップ日:",
      totalItems: "総アイテム数:",
      row: "行",
      quantity: "数量",
      available: "利用可能",
      status: "ステータス",
      cancel: "キャンセル",
      createBulkRequest: "一括リクエストを作成",
      noValidItemsToSubmit: "送信する有効なアイテムがありません",
      successfullyCreatedBulkRequest: "一括リクエストが正常に作成されました:",
      errorCreatingBulkRequest: "一括リクエスト作成エラー:",
      errorSubmittingBulkRequest: "一括リクエスト送信エラー:",
      errorExportingData: "データエクスポートエラー:",
      requestNumber: "リクエスト番号",
      createdAt: "作成日時",
      requestType: "タイプ",
      overallStatus: "全体ステータス",
      createdBy: "作成者",
      unknown: "不明",
      existingItems: "既存アイテム",
      addMoreItems: "さらにアイテムを追加",
      lineItems: "明細アイテム",
      lineNumber: "行#",
      actions: "操作",
      esp32Only: "ESP32のみ",
      onlyESP32CanComplete: "進行中のアイテムを完了できるのはESP32のみです",
      complete: "完了",
      noLineItemsFound: "明細アイテムが見つかりません",
      addMoreItemsHeader: "さらにアイテムを追加",
      addMoreItemsInstruction: "このピッキングリクエストにさらにアイテムを追加できます。アイテムは同じピックアップ日に追加されます",
      addSingleItem: "単一アイテムを追加",
      addIndividualItems: "アイテムを1つずつ追加",
      addItem: "アイテムを追加",
      uploadCSV: "CSVをアップロード",
      bulkAddFromCSV: "CSVファイルからアイテムを一括追加",
      addSingleItemForm: "単一アイテムを追加",
      itemsToAdd: "追加するアイテム",
      clearAll: "すべてクリア",
      addAllItems: "すべてのアイテムを追加",
      close: "閉じる",
      saveChanges: "変更を保存",
      pleaseCompleteAllFields: "すべてのフィールドに入力してください",
      quantityMustBePositive: "数量は0より大きい必要があります",
      requestUpdatedSuccessfully: "リクエストが正常に更新されました!",
      errorUpdatingRequest: "リクエスト更新エラー:",
      confirmDeleteRequest: "本当にこのリクエストを削除してもよろしいですか？",
      requestDeletedSuccessfully: "リクエストが正常に削除されました!",
      errorDeletingRequest: "リクエスト削除エラー:",
      itemAlreadyInCart: "アイテムは既にカートに存在します。数量を更新しますか？",
      itemNotFoundInInventory: "アイテムが在庫に見つかりません",
      insufficientInventoryAvailable: "在庫不足。利用可能:",
      requested: "リクエスト:",
      errorCheckingInventoryTryAgain: "在庫確認エラー。もう一度お試しください。",
      itemAddedToCart: "アイテムがカートに正常に追加されました!",
      confirmRemoveFromCart: "本当にカートから削除してもよろしいですか？",
      itemRemovedFromCart: "アイテムがカートから削除されました",
      noItemsInCart: "カートにアイテムがありません",
      qtyShort: "数量:",
      availableShort: "利用可能:",
      pleaseAddAtLeastOneItem: "カートに少なくとも1つのアイテムを追加してください",
      pleaseSelectPickupDate: "ピックアップ日を選択してください",
      checkingInventory: "在庫を確認中...",
      insufficientStock: "在庫不足",
      errorCheckingInventory: "在庫確認エラー",
      bulkRequestSubmittedSuccessfully: "一括リクエストが正常に送信されました!",
      itemAlreadyInEditCart: "アイテムは既に編集カートに存在します。数量を更新しますか？",
      itemAddedToEditCart: "アイテムが編集カートに追加されました!",
      confirmRemoveFromEditCart: "編集カートから削除しますか？",
      itemRemovedFromEditCart: "アイテムが編集カートから削除されました",
      confirmClearEditCart: "編集カート内のすべてのアイテムをクリアしますか？",
      editCartCleared: "編集カートがクリアされました",
      partNumberBackNumberNotFound: "品番と背番号の組み合わせがマスターデータベースに見つかりません",
      errorValidatingMasterData: "マスターデータ検証エラー",
      physicalStockCSV: "物理在庫",
      reservedStockCSV: "予約済み在庫",
      availableStockCSV: "利用可能在庫",
      lastUpdatedCSV: "最終更新日時",

      // Inventory Tab Specific
      inventoryTitle: "在庫管理",
      inventorySubtitle: "二段階在庫追跡システム",
      addInventory: "在庫を追加",
      inventoryItems: "在庫アイテム",
      inventoryTransactions: "在庫取引",
      totalItems: "総アイテム数",
      physicalStock: "物理在庫",
      reservedStock: "予約済み在庫",
      availableStock: "利用可能在庫",
      quantityToAdd: "追加数量",
      searchInventory: "在庫を検索...",
      itemsPerPage: "ページあたりのアイテム数",
      
      // NODA Tab Specific
      nodaTitle: "NODA倉庫管理",
      nodaSubtitle: "倉庫ピッキングオーダー管理システム",
      pickingRequests: "ピッキングリクエスト",
      pickingRequestDetails: "ピッキングリクエスト詳細",
      bulkPickingRequest: "一括ピッキングリクエスト",
      addItems: "アイテムを追加",
      reviewCart: "カートを確認",
      submit: "送信",
      pickupDateAllItems: "ピックアップ日（全アイテム）",
      addItemToCart: "カートに追加",
      enterPartNumber: "品番を入力",
      enterBackNumber: "背番号を入力",
      qtyPlaceholder: "数量",
      cartItems: "カートアイテム",
      proceedToReview: "カートを確認",
      backToAddItems: "アイテム追加に戻る",
      proceedToSubmit: "送信に進む",
      readyToSubmit: "送信準備完了",
      bulkPickingRequestReady: "一括ピッキングリクエストの送信準備が整いました。",
      submittingBulkRequest: "一括リクエストを送信中...",
      backToReview: "確認に戻る",
      submitBulkRequest: "一括リクエストを送信",
      itemsToRequest: "リクエストするアイテム",
      searchRequests: "リクエストを検索...",
      allStatuses: "すべてのステータス",
      
      // Alert Messages for NODA
      alertInventoryError: "在庫エラー: アイテムが在庫データベースに見つかりません。\n\n背番号を確認してもう一度お試しください。",
      alertInsufficientInventory: "在庫不足!",
      alertRequested: "リクエスト:",
      alertAvailable: "利用可能:",
      alertReduceQuantity: "数量を減らすか、在庫レベルを確認してください。",
      alertErrorCheckingInventory: "在庫確認エラー: ",
      alertRequestCreatedSuccess: "リクエストが正常に作成されました!",
      alertRequestNumber: "リクエスト番号:",
      alertErrorCreatingRequest: "リクエスト作成エラー: ",
      alertErrorExportingData: "データエクスポートエラー: ",
      alertNoDataToExport: "エクスポートするデータがありません",
      alertErrorLoadingRequestDetails: "リクエスト詳細の読み込みエラー: ",
      alertFillAllFields: "すべてのフィールドに入力してください",
      alertQuantityGreaterThanZero: "数量は0より大きい必要があります",
      alertItemExistsInCart: "アイテム {backNumber} は既にカートに存在します。数量を更新しますか？",
      alertItemNotFoundInInventory: "アイテムが在庫に見つかりません",
      alertErrorCheckingInventoryTryAgain: "在庫確認エラー。もう一度お試しください。",
      alertItemAddedToCart: "アイテム {backNumber} がカートに正常に追加されました!",
      alertAddAtLeastOneItem: "カートに少なくとも1つのアイテムを追加してください",
      alertSelectPickupDate: "ピックアップ日を選択してください",
      alertNoItemsToSubmit: "送信するカートアイテムがありません",
      alertBulkRequestSubmitted: "一括リクエストが正常に送信されました!",
      alertProcessedItems: "処理済みアイテム:",
      alertFailedItems: "失敗アイテム:",
      alertFailedSubmitBulkRequest: "一括リクエストの送信に失敗しました",
      alertErrorSubmittingBulkRequest: "一括リクエスト送信エラー: ",
      alertRequestUpdatedSuccess: "リクエストが正常に更新されました!",
      alertErrorUpdatingRequest: "リクエスト更新エラー: ",
      alertRequestDeletedSuccess: "リクエストが正常に削除されました!",
      alertErrorDeletingRequest: "リクエスト削除エラー: ",
      alertConfirmDeleteRequest: "このリクエストを削除してもよろしいですか？",
      alertConfirmRemoveFromCart: "{backNumber} をカートから削除してもよろしいですか？",
      alertItemRemovedFromCart: "アイテム {backNumber} がカートから削除されました",
      alertErrorUpdatingLineItem: "明細アイテムのステータス更新エラー: ",
      alertMarkLineItemCompleted: "明細アイテム {lineNumber} を完了済みにしますか？",
      alertItemExistsInEditCart: "アイテム {backNumber} は既に編集カートに存在します。数量を更新しますか？",
      alertNoItemsInEditCart: "編集カートに追加するアイテムがありません",
      alertItemsAddedSuccess: "アイテムが正常に追加されました!",
      alertAddedItems: "追加されたアイテム:",
      alertFailedAddItems: "アイテムの追加に失敗しました",
      alertErrorAddingItems: "リクエストへのアイテム追加エラー: ",
      alertSelectCsvFile: "CSVファイルを選択してください",
      alertCsvFileEmpty: "CSVファイルが空です",
      alertInvalidCsvFormat: "無効なCSV形式。ヘッダーには品番または背番号が含まれている必要があります",
      alertCsvProcessed: "CSV処理完了: {success} アイテム追加、{failed} 失敗",
      alertErrorParsingCsv: "CSVファイル解析エラー: ",
      alertConfirmRemoveFromEditCart: "{backNumber} を編集カートから削除しますか？",
      alertItemRemovedFromEditCart: "アイテム {backNumber} が編集カートから削除されました",
      alertConfirmClearEditCart: "編集カートの全アイテムをクリアしますか？",
      alertEditCartCleared: "編集カートがクリアされました",
      unknownError: "不明なエラー",

    }
  };

  let currentLang = localStorage.getItem("lang") || "en";
  
  function t(key) {
    return translations[currentLang][key] || key;
  }
  
  function applyLanguage() {
    // Apply translations to elements with data-i18n attributes
    document.querySelectorAll("[data-i18n]").forEach(el => {
      const key = el.getAttribute("data-i18n");
      if (translations[currentLang][key]) {
        el.textContent = translations[currentLang][key];
      }
    });
  
    // Apply translations to placeholders
    document.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
      const key = el.getAttribute("data-i18n-placeholder");
      if (translations[currentLang][key]) {
        el.placeholder = translations[currentLang][key];
      }
    });
    
    // Apply translations to titles
    document.querySelectorAll("[data-i18n-title]").forEach(el => {
      const key = el.getAttribute("data-i18n-title");
      if (translations[currentLang][key]) {
        el.title = translations[currentLang][key];
      }
    });
  
    // Update search input placeholder
    const search = document.getElementById("searchInput");
    if (search) {
      search.placeholder = translations[currentLang].searchPlaceholder;
    }
    
    // Update page title based on current page
    const currentPage = getCurrentPage();
    if (currentPage && translations[currentLang][currentPage + "Title"]) {
      document.title = translations[currentLang][currentPage + "Title"] + " - Freya Admin";
    }
  }
  
  function getCurrentPage() {
    // Try to determine current page from various indicators
    const activeNav = document.querySelector(".nav-btn.bg-gray-100");
    if (activeNav) {
      return activeNav.getAttribute("data-page");
    }
    return "dashboard"; // default
  }
  
  // Make translation function globally available
  window.t = t;
  window.applyLanguage = applyLanguage;

const languageSelector = document.getElementById("languageSelector");
if (languageSelector) {
  languageSelector.value = currentLang;
  languageSelector.addEventListener("change", (e) => {
    currentLang = e.target.value;
    localStorage.setItem("lang", currentLang);
    applyLanguageEnhanced();
    
    // Trigger a custom event to notify other parts of the app
    window.dispatchEvent(new CustomEvent('languageChanged', { 
      detail: { language: currentLang } 
    }));
    
    // If there's a current page loaded, refresh its content
    const currentPage = getCurrentPage();
    if (currentPage && typeof loadPage === 'function') {
      loadPage(currentPage);
    }
  });
}

// Apply language on initial load
applyLanguageEnhanced();

// Listen for page changes to reapply translations
window.addEventListener('pageLoaded', () => {
  applyLanguageEnhanced();
});

// Enhanced function to handle dynamic content translation
function translateDynamicContent(container) {
  if (!container) container = document;
  
  // Apply translations to new elements with data-i18n attributes
  container.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    if (translations[currentLang][key]) {
      el.textContent = translations[currentLang][key];
    }
  });

  // Apply translations to new placeholders
  container.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
    const key = el.getAttribute("data-i18n-placeholder");
    if (translations[currentLang][key]) {
      el.placeholder = translations[currentLang][key];
    }
  });
  
  // Apply translations to new titles
  container.querySelectorAll("[data-i18n-title]").forEach(el => {
    const key = el.getAttribute("data-i18n-title");
    if (translations[currentLang][key]) {
      el.title = translations[currentLang][key];
    }
  });
}

// Enhanced apply language function
function applyLanguageEnhanced() {
  applyLanguage();
  translateDynamicContent();
  
  // Also handle common button texts that might not have data-i18n
  const buttons = document.querySelectorAll('button');
  buttons.forEach(button => {
    const text = button.textContent.trim();
    if (text === 'Edit' || text === '編集') {
      if (!button.hasAttribute('data-i18n')) {
        button.textContent = t('edit');
      }
    }
    if (text === 'Delete' || text === '削除') {
      if (!button.hasAttribute('data-i18n')) {
        button.textContent = t('delete');
      }
    }
    if (text === 'Reset Password' || text === 'パスワードリセット') {
      if (!button.hasAttribute('data-i18n')) {
        button.textContent = t('resetPassword');
      }
    }
  });
}

// Make the enhanced function globally available
window.translateDynamicContent = translateDynamicContent;
window.applyLanguageEnhanced = applyLanguageEnhanced;
